# Generated by Django 4.2.6 on 2023-11-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcita',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
