# Generated by Django 4.2.6 on 2023-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0002_alter_solicitudcita_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='time',
            field=models.TimeField(),
        ),
    ]
