# Generated by Django 4.2.6 on 2023-11-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0003_alter_evento_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='start',
            field=models.DateField(),
        ),
    ]
