# Generated by Django 4.2.6 on 2023-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0004_alter_evento_color_alter_evento_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
