# Generated by Django 4.2.6 on 2023-11-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0005_usuario_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='temp_password',
        ),
    ]
