# Generated by Django 3.0.3 on 2023-11-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0006_remove_usuario_temp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcita',
            name='hora_cita',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
