# Generated by Django 3.0.3 on 2023-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0007_auto_20231126_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcita',
            name='ficha',
            field=models.CharField(default=2503327, max_length=10),
            preserve_default=False,
        ),
    ]
