# Generated by Django 4.2.6 on 2023-11-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0008_solicitudcita_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('evento', 'Evento'), ('cita', 'Cita')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
