# Generated by Django 4.2.6 on 2023-12-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0009_evento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcita',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
